name: Deploy

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to deploy'
        required: true
        default: 'accesscontrol-api'
      version:
        description: 'Version to deploy'
        required: true
        default: 'main'
  push:

env:
  DOMAIN: utopiklab.net
  PROJECT: ${{ github.event.inputs.project }}
  VERSION: ${{ github.event.inputs.version }} 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Set up manifest"
        run: |
          envsubst < manifests/$PROJECT.yaml > temp.yaml && \
            mv temp.yaml manifests/$PROJECT.yaml
          cat manifests/$PROJECT.yaml

      - name: "Deploy: $PROJECT"
        uses: actions-hub/kubectl@v1.29.2
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f manifests/$PROJECT.yaml
