name: Deploy All Projects

on:
  push:

jobs:
  deploy_all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: 
          - accesscontrol-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call Deploy Workflow
        uses: ./.github/workflows/deploy.yaml
        with:
          project: ${{ matrix.project }}

      # - name: Loop over projects
      #   run: |
      #     ref=$(basename "${{ github.ref }}")
      #     echo "Deploying ${{ matrix.project }}..."
      #     # Call the 'deploy' workflow for each project
      #     curl POST -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yaml/dispatches \
      #       -d "{\"ref\":\"$ref\", \"inputs\": {\"project\": \"${{ matrix.project }}\"}}" --trace -
