name: Deploy All Projects

on:
  push:

env:
  PROJECTS: ("accesscontrol-api")

jobs:
  deploy_all:
    runs-on: ubuntu-latest

    steps:
      - name: Loop over projects
        run: |
          ref=$(basename "${{ github.ref }}")
          for project in "${PROJECTS[@]}"; do
            echo "Deploying $project..."
            # Call the 'deploy' workflow for each project
            curl -v -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yaml/dispatches \
                -d '{"ref":"$ref")", "inputs": {"project": "$project"}}' --trace -
          done
