name: Deploy

on:
  workflow_dispatch:
  push:

env:
  DOMAIN: utopiklab.net

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          envsubst < manifests/accesscontrol-api.yaml > temp.yaml && \
            mv temp.yaml manifests/accesscontrol-api.yaml
          cat manifests/accesscontrol-api.yaml

      - name: "Deploy: accesscontrol-api"
        uses: actions-hub/kubectl@v1.29.2
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          REGISTRY: ghcr.io
          VERSION: main
        with:
          args: apply -f manifests/accesscontrol-api.yaml
