name: Deploy All Projects

on:
  push:
  workflow_dispatch:

env:
  HOST: sandcastle.utopiklab.net
  REGISTRY: ghcr.io
  VERSION: pr.22

jobs:
  deploy-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: 
          - accesscontrol-api

    env:
      PROJECT: ${{ matrix.project }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Set up manifest"
        run: |
          envsubst < manifests/$PROJECT.yaml > temp.yaml && \
            mv temp.yaml manifests/$PROJECT.yaml
          cat manifests/$PROJECT.yaml

      - name: "Deploy ${{ env.PROJECT }}"
        uses: actions-hub/kubectl@v1.29.2
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f manifests/${{ env.PROJECT }}.yaml
